export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        theme: {
          light: {
            bg: "#F9FAFB",
            surface: "#FFFFFF",
            surfaceAlt: "#E8EDE6",
            sidebar: "#D6DFD3",
            sidebarStart: "#E9EEE7",
            sidebarMiddle: "#E3EBE0",
            sidebarEnd: "#D6DFD3",
            textPrimary: "#374151",
            textSecondary: "#6B7280",
            textDisabled: "#9CA3AF",
            heading: "#3F4F3C",
            border: "#E5E7EB",
            borderStrong: "#D1D5DB",
            primaryButton: "#5F6F5C",
            primaryHover: "#4E5D4B",
            danger: "#EF5350",
            warning: "#FBBF24",
            warningText: "#3D2C00",
            info: "#29B6F6",
            inputBg: "#FFFFFF",
            inputBorder: "#D1D5DB",
            focusBorder: "#5F6F5C",
          },
          dark: {
            bg: "#212121",
            surface: "#2C2C2C",
            surfaceAlt: "#2C2C2C",
            sidebar: "#1A1A1A",
            sidebarStart: "#1A1A1A",
            sidebarMiddle: "#1A1A1A",
            sidebarEnd: "#1A1A1A",
            textPrimary: "#FFFFFF",
            textSecondary: "#B0B0B0",
            textDisabled: "#6B7280",
            heading: "#FFFFFF",
            border: "#3A3A3A",
            borderStrong: "#444444",
            primaryButton: "#464747",
            primaryHover: "#464747",
            danger: "#EF5350",
            warning: "#FFA726",
            warningText: "#212121",
            info: "#29B6F6",
            inputBg: "#2C2C2C",
            inputBorder: "#444444",
            focusBorder: "#4CAF50",
          },
        },
      },
    },
  },
  plugins: [],
};
